version: '3'
services:
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_USER: 'tutorial'
            MYSQL_PASSWORD: 'secret'
            MYSQL_DATABASE: 'tutorial'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
    moodle:
        build: https://raw.githubusercontent.com/carlos-lima/upecloud/master/webserver/dockerfile
        ports:
            - 8080:8080
        depends_on: 
            - mysql
        deploy:
            resources:
                limits:
                    cpus: '0.1'
                    memory: 20M
                reservations:
                    cpus: '0.01'
                    memory: 15M            
volumes:
    mysqldata: {}