FROM ubuntu:latest

RUN apt -y update && apt -y upgrade; \
    apt-get install -y software-properties-common tzdata; \
    add-apt-repository -y ppa:ondrej/php; \
    apt-get -y update; \
    apt-get install -y php7.3 \
                       php7.3-curl \
                       php7.3-zip \
                       php7.3-mysql \
                       php7.3-xml \
                       php7.3-mbstring \
                       php7.3-gd \
                       php7.3-soap \
                       php7.3-xmlrpc \
                       php7.3-intl;

RUN sed -i 's/80/8080/g' /etc/apache2/ports.conf ; \
    sed -i 's/\/html/\/html\/moodle/g' /etc/apache2/sites-enabled/000-default.conf
    
ADD https://download.moodle.org/download.php/direct/stable310/moodle-latest-310.tgz /var/www/

RUN cd /var/www/ ;\
    tar -xzvf *.tgz ;\
    rm -f *.tgz

RUN chmod -R +x /var/www/moodle ; \
    chown -R 0:0 /var/www/moodle ; \
    rm -fr /var/www/html ; \
    mv /var/www/moodle /var/www/html

CMD apachectl -D FOREGROUND

EXPOSE 8080